import 'dotenv/config'
import express, { NextFunction, Request, Response } from 'express'
import cors from 'cors'
import cookieParser from 'cookie-parser'
import bcrypt from 'bcryptjs'
import jwt, { SignOptions } from 'jsonwebtoken'
import crypto from 'node:crypto'
import http from 'node:http'
import cron from 'node-cron'
import { Server } from 'socket.io'
import { PrismaClient, Role, TaskStatus, ActivityType } from '@prisma/client'
import { z } from 'zod'
import nodemailer from 'nodemailer'

const prisma = new PrismaClient(); const app = express(); const server = http.createServer(app); const allowedOrigin = (origin?: string) => process.env.NODE_ENV !== 'production' && origin ? /^https?:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin) : origin === process.env.CLIENT_URL; const io = new Server(server, { cors: { origin: allowedOrigin, credentials: true } });
const accessSecret = process.env.JWT_ACCESS_SECRET ?? 'dev-access-secret'; const refreshSecret = process.env.JWT_REFRESH_SECRET ?? 'dev-refresh-secret';
const mailer = process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASSWORD ? nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT ?? 587), secure: Number(process.env.SMTP_PORT ?? 587) === 465, auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASSWORD } }) : null;
const inviteSchema = z.object({ name: z.string().trim().min(2).max(100), email: z.string().email(), role: z.enum(['ADMIN', 'PM', 'DEVELOPER']) });
type Claims = { sub: string; role: Role; name: string }; type AuthedRequest = Request & { user?: Claims }
const asyncRoute = (handler: (req: AuthedRequest, res: Response) => Promise<unknown>) => (req: AuthedRequest, res: Response, next: NextFunction) => handler(req, res).catch(next)
const token = (user: { id: string; role: Role; name: string }, secret: string, expiresIn: SignOptions['expiresIn']) => jwt.sign({ sub: user.id, role: user.role, name: user.name }, secret, { expiresIn })
const auth = (req: AuthedRequest, res: Response, next: NextFunction) => { try { req.user = jwt.verify((req.headers.authorization ?? '').replace('Bearer ', ''), accessSecret) as Claims; next() } catch { res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'A valid access token is required.' } }) } }
const allow = (...roles: Role[]) => (req: AuthedRequest, res: Response, next: NextFunction) => req.user && roles.includes(req.user.role) ? next() : res.status(403).json({ error: { code: 'FORBIDDEN', message: 'You do not have access to this resource.' } })
const unreadCount = async (userId: string) => prisma.notification.count({ where: { userId, readAt: null } });
const notify = async (userId: string, message: string, taskId?: number) => { const notification = await prisma.notification.create({ data: { userId, message, taskId } }); io.to(`user:${userId}`).emit('notification:new', notification); io.to(`user:${userId}`).emit('notification:count', await unreadCount(userId)); return notification; };
app.post('/api/team/invite', auth, allow(Role.ADMIN, Role.PM), asyncRoute(async (req, res) => { const input = inviteSchema.parse(req.body); if (!mailer) return void res.status(503).json({ error: { code: 'MAIL_NOT_CONFIGURED', message: 'SMTP email delivery is not configured.' } }); await mailer.sendMail({ from: process.env.MAIL_FROM, to: input.email, subject: 'You are invited to Atelier Studio', text: `Hi ${input.name},\n\nYou have been invited to join Atelier Studio as a ${input.role === 'PM' ? 'Project Manager' : input.role === 'DEVELOPER' ? 'Developer' : 'Administrator'}.\n\nPlease contact your administrator for your account setup.`, html: `<p>Hi ${input.name},</p><p>You have been invited to join <strong>Atelier Studio</strong> as a ${input.role === 'PM' ? 'Project Manager' : input.role === 'DEVELOPER' ? 'Developer' : 'Administrator'}.</p><p>Please contact your administrator for your account setup.</p>` }); res.status(202).json({ delivered: true, email: input.email }) }));
const createTaskSchema = z.object({ title: z.string().trim().min(1).max(160), projectId: z.string(), developerId: z.string(), priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']), dueDate: z.coerce.date() });
app.post('/api/tasks', auth, allow(Role.ADMIN, Role.PM), asyncRoute(async (req, res) => { const input = createTaskSchema.parse(req.body); const project = await prisma.project.findUniqueOrThrow({ where: { id: input.projectId } }); if (req.user!.role === Role.PM && project.ownerId !== req.user!.sub) return void res.status(403).json({ error: { code: 'PROJECT_SCOPE', message: 'You can only add tasks to your projects.' } }); const task = await prisma.task.create({ data: { title: input.title, projectId: input.projectId, developerId: input.developerId, priority: input.priority, dueDate: input.dueDate } }); await notify(input.developerId, `You were assigned Task #${task.id}: ${task.title}`, task.id); res.status(201).json(task) }));
const signInSchema = z.object({ email: z.string().email(), password: z.string().min(8) }); const statusSchema = z.object({ status: z.nativeEnum(TaskStatus) });
app.use(cors({ origin: allowedOrigin, credentials: true })); app.use(express.json()); app.use(cookieParser());
app.post('/api/auth/login', asyncRoute(async (req, res) => { const input = signInSchema.parse(req.body); const user = await prisma.user.findUnique({ where: { email: input.email } }); if (!user || !(await bcrypt.compare(input.password, user.passwordHash))) return void res.status(401).json({ error: { code: 'INVALID_CREDENTIALS', message: 'Email or password is incorrect.' } }); const accessToken = token(user, accessSecret, '15m'); const refreshToken = token(user, refreshSecret, '7d'); await prisma.refreshToken.create({ data: { tokenHash: crypto.createHash('sha256').update(refreshToken).digest('hex'), expiresAt: new Date(Date.now() + 7 * 86400000), userId: user.id } }); res.cookie('refreshToken', refreshToken, { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax', maxAge: 7 * 86400000 }); res.json({ accessToken, user: { id: user.id, name: user.name, role: user.role } }) }))
app.post('/api/auth/refresh', asyncRoute(async (req, res) => { const refresh = req.cookies.refreshToken; if (!refresh) return void res.status(401).json({ error: { code: 'NO_REFRESH_TOKEN', message: 'Refresh token is missing.' } }); try { const claims = jwt.verify(refresh, refreshSecret) as Claims; const saved = await prisma.refreshToken.findUnique({ where: { tokenHash: crypto.createHash('sha256').update(refresh).digest('hex') } }); if (!saved || saved.expiresAt < new Date()) throw new Error(); const user = await prisma.user.findUniqueOrThrow({ where: { id: claims.sub } }); res.json({ accessToken: token(user, accessSecret, '15m') }) } catch { res.status(401).json({ error: { code: 'INVALID_REFRESH_TOKEN', message: 'Refresh token is invalid.' } }) } }))
app.get('/api/dashboard', auth, asyncRoute(async (req, res) => { const where = req.user!.role === Role.DEVELOPER ? { developerId: req.user!.sub } : req.user!.role === Role.PM ? { project: { ownerId: req.user!.sub } } : {}; const [tasks, projects, overdue, online] = await Promise.all([prisma.task.groupBy({ by: ['status'], where, _count: true }), prisma.project.count(req.user!.role === Role.PM ? { where: { ownerId: req.user!.sub } } : undefined), prisma.task.count({ where: { ...where, status: TaskStatus.OVERDUE } }), Promise.resolve(io.engine.clientsCount)]); res.json({ projects, tasksByStatus: tasks, overdue, online }) }))
app.get('/api/tasks', auth, asyncRoute(async (req, res) => { const query = z.object({ status: z.nativeEnum(TaskStatus).optional(), priority: z.string().optional(), from: z.coerce.date().optional(), to: z.coerce.date().optional() }).parse(req.query); const scope = req.user!.role === Role.DEVELOPER ? { developerId: req.user!.sub } : req.user!.role === Role.PM ? { project: { ownerId: req.user!.sub } } : {}; const tasks = await prisma.task.findMany({ where: { ...scope, status: query.status, priority: query.priority as never, dueDate: { gte: query.from, lte: query.to } }, include: { project: true, developer: { select: { name: true } } }, orderBy: [{ priority: 'desc' }, { dueDate: 'asc' }] }); res.json(tasks) }))
app.patch('/api/tasks/:id/status', auth, allow(Role.ADMIN, Role.PM, Role.DEVELOPER), asyncRoute(async (req, res) => { const { status } = statusSchema.parse(req.body); const id = Number(req.params.id); const task = await prisma.task.findUniqueOrThrow({ where: { id }, include: { project: true } }); if (req.user!.role === Role.DEVELOPER && task.developerId !== req.user!.sub) return void res.status(403).json({ error: { code: 'TASK_SCOPE', message: 'Developers can only update assigned tasks.' } }); if (req.user!.role === Role.PM && task.project.ownerId !== req.user!.sub) return void res.status(403).json({ error: { code: 'PROJECT_SCOPE', message: 'PMs can only update tasks in their projects.' } }); const updated = await prisma.$transaction(async (tx) => { const result = await tx.task.update({ where: { id }, data: { status } }); await tx.activity.create({ data: { type: ActivityType.STATUS_CHANGED, fromStatus: task.status, toStatus: status, message: `${req.user!.name} moved Task #${id} from ${task.status} to ${status}`, userId: req.user!.sub, projectId: task.projectId, taskId: id } }); return result }); if (status === TaskStatus.IN_REVIEW && task.developerId) await notify(task.project.ownerId, `Task #${id} is ready for review.`, id); io.to(`project:${task.projectId}`).emit('activity:new', { taskId: id, status }); res.json(updated) }))
app.get('/api/activity', auth, asyncRoute(async (req, res) => { const scope = req.user!.role === Role.DEVELOPER ? { task: { developerId: req.user!.sub } } : req.user!.role === Role.PM ? { project: { ownerId: req.user!.sub } } : {}; res.json(await prisma.activity.findMany({ where: scope, include: { user: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 20 })) }))
app.get('/api/notifications', auth, asyncRoute(async (req, res) => res.json(await prisma.notification.findMany({ where: { userId: req.user!.sub }, orderBy: { createdAt: 'desc' }, take: 30 }))))
app.patch('/api/notifications/:id/read', auth, asyncRoute(async (req, res) => res.json(await prisma.notification.updateMany({ where: { id: String(req.params.id), userId: req.user!.sub }, data: { readAt: new Date() } }))))
app.post('/api/notifications/read-all', auth, asyncRoute(async (req, res) => { const result = await prisma.notification.updateMany({ where: { userId: req.user!.sub, readAt: null }, data: { readAt: new Date() } }); io.to(`user:${req.user!.sub}`).emit('notification:count', 0); res.json(result) }))
app.use((err: unknown, _req: Request, res: Response, _next: NextFunction) => { if (err instanceof z.ZodError) return res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Request validation failed.', details: err.flatten() } }); console.error(err); res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Something went wrong.' } }) })
io.use((socket, next) => { try { socket.data.user = jwt.verify(socket.handshake.auth.token, accessSecret) as Claims; next() } catch { next(new Error('Unauthorized')) } }); io.on('connection', async (socket) => { const user = socket.data.user as Claims; socket.join(`user:${user.sub}`); const projects = await prisma.project.findMany({ where: user.role === Role.ADMIN ? {} : user.role === Role.PM ? { ownerId: user.sub } : { tasks: { some: { developerId: user.sub } } }, select: { id: true } }); projects.forEach((project) => socket.join(`project:${project.id}`)); socket.emit('notification:count', await unreadCount(user.sub)); io.emit('presence:count', io.engine.clientsCount); socket.on('disconnect', () => io.emit('presence:count', io.engine.clientsCount)) });
cron.schedule('0 * * * *', async () => { await prisma.task.updateMany({ where: { dueDate: { lt: new Date() }, status: { notIn: [TaskStatus.DONE, TaskStatus.OVERDUE] } }, data: { status: TaskStatus.OVERDUE } }) })
server.listen(Number(process.env.PORT ?? 4000), () => console.log(`API listening on ${process.env.PORT ?? 4000}`))